Highlight that annotations are available
fairfaxmedia/charts pull request #26
Opened 2019-07-11 00:55 UTC by bluebenno

Highlight that annotations can be placed into the deployment and onto the pods.  
This is often useful for kiam or kube2iam, to access AWS IAM roles.

2019-07-11 04:11 UTC, egeland approved these changes

2019-07-11 04:12 UTC, egeland requested changes

2019-07-11 04:12 UTC, egeland commented on stable/confidant/README.md
> +| `annotations`                           | ``                                                                  | ..          |
The default value is not empty, it's `{}`, so you should put that here...

2019-07-15 23:06 UTC, egeland approved these changes

2019-07-15 23:06 UTC, egeland approved these changes

2019-07-20 05:13 UTC, matthope approved these changes

2019-07-22 01:38 UTC, merged